### ISSUE TITLE
Literature review on API transmission

### ISSUE THREAD

**Issue by himanshunaidu** [TaskarCenterAtUW/iOSPointMapper#61]
Literature review on the possible use of the TDEI API for transmission of data in OpenSideWalk-schema-compatible format

**Comment by himanshunaidu** [comment]
Note: The APIs for the data transmission that we are supposed to use, also seem to be used by another app called GoInfoGame:
https://github.com/TaskarCenterAtUW/GoInfoGame-iOS

We will be reviewing this app as next steps.

**Comment by himanshunaidu** [comment]
https://github.com/TaskarCenterAtUW/TDEI-gateway

**Comment by himanshunaidu** [comment]
https://tdei-api-gateway-spec-stage.azurewebsites.net/#/General/listDatasetFiles

**Comment by mariana0412** [comment]
- Authentication on the server: POST
[/api/v1/authenticate](https://tdei-api-gateway-spec-stage.azurewebsites.net/#/Authentication/authenticate)
But you need to be registered somehow not using this API. This auth request returns 404 with error "User not found".

- OSW endpoints take datasets, not specific POIs. 
"OSW file which is expected to be a zip file, internally has {nodes, edges, points}.geojson. If the extensions are present, then the zip file will have {nodes, edges, points}.extension.geojson files" 
About GeoJSON files: https://support.planet.com/hc/en-us/articles/360016337117-Creating-a-GeoJSON-file

- In order to use we also need tdei_project_group_id and tdei_service_id parameters. As for request body, there should be a dataset, mentioned above, and [metadata](https://raw.githubusercontent.com/TaskarCenterAtUW/TDEI-osw-datasvc-ts/stage/schema/metadata.schema.json)

**Comment by himanshunaidu** [comment]
This discussion provides important context:
https://github.com/TaskarCenterAtUW/iOSPointMapper/discussions/70

**Comment by himanshunaidu** [comment]
## Some additional links

### TDEI Workspaces

1. TDEI Account Creation: https://docs.google.com/document/d/1Rt1uCMEh82dR3cv4kC0XmkW3q_xPYuR3/edit

2. Workspaces Demo: https://docs.google.com/document/d/1egCHtY2nkbToye8FyzcgkH4K2EKwxikx/edit

3. TDEI Account Creation: https://docs.google.com/document/d/1Rt1uCMEh82dR3cv4kC0XmkW3q_xPYuR3/edit

### GoInfoGame

1. GoInfoGame Manual: https://docs.google.com/document/d/1n7KS2J34oZnJcdqPMORm-vZ1Rf8xM80PaRIvTIjZbkM/edit?tab=t.0

2. GoInfoGame Demo: https://docs.google.com/document/d/1lgkDgrYnk6sZFzulJpDNn0PUp_hEUzhg/edit

**Comment by himanshunaidu** [comment]
Questions to ponder about:
1. There is some confusion on how all the workspaces connect together
https://workspaces-stage.sidewalks.washington.edu/
This seems to be the one we use for Workspaces. 

https://workspaces-dev.sidewalks.washington.edu/
This seems to be the dev version of Workspaces. But I am facing issues logging in to this one.

**Comment by himanshunaidu** [comment]
Final documentation for API reference: https://docs.google.com/document/d/1qPSW5pYmVb-RXOiryBm452sLfTvFl38f_TCO4SElkSY/edit?tab=t.0#heading=h.8j2g0idp8eng

**Comment by himanshunaidu** [comment]
Closing this for now as we are fine with the API details that we already have
